modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="rss_space_mod"
version="0.0.4"
displayName="RSS Space Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="RedstoneStick, MCreator"

[[dependencies.rss_space_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.rss_space_mod]]
    modId="  chipped"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rss_space_mod]]
    modId="  supplementaries"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rss_space_mod]]
    modId=" immersiveengineering"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rss_space_mod]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

